import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "m-0UH7ubJCj5g-B01Tea8Q0GNvea", // <-- yahan apna Google wala code daalna
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 
  <head>
  <meta name="google-site-verification" content="fa7lYREdyXrdZSqLUzZdPa0KQ8tP1KAS3Jb05P5p7rE" />
  </head>

      <body className={inter.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
